apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: db:5432
    user: energy
    secureJsonData:
      password: energy
    jsonData:
      database: energy
      sslmode: disable
      postgresVersion: 16
      timescaledb: true
      timeInterval: 1s
    isDefault: true
